"""
Multi-Framework Standalone Backend Generator for Site Studio Templates.
Generates complete, production-ready, standalone REST API backends
with local SQLite database persistence, CORS middleware, and CRUD endpoints
for FastAPI, Express.js, NestJS, Django, Spring Boot, Ruby on Rails, Laravel, and Actix Web.
"""

from typing import Dict, Any


def generate_standalone_backend(
    framework: str = "fastapi",
    title: str = "Site Studio Template",
    business_type: str = "Business",
) -> Dict[str, str]:
    """
    Generates a dict of relative file paths -> file contents for the requested backend framework.
    """
    fw_lower = (framework or "fastapi").lower().strip()

    if fw_lower == "express" or fw_lower == "nodejs" or fw_lower == "node":
        return _generate_express_backend(title, business_type)
    elif fw_lower == "nestjs" or fw_lower == "nest":
        return _generate_nestjs_backend(title, business_type)
    elif fw_lower == "django":
        return _generate_django_backend(title, business_type)
    elif fw_lower == "springboot" or fw_lower == "spring" or fw_lower == "java":
        return _generate_springboot_backend(title, business_type)
    elif fw_lower == "rails" or fw_lower == "ruby":
        return _generate_rails_backend(title, business_type)
    elif fw_lower == "laravel" or fw_lower == "php":
        return _generate_laravel_backend(title, business_type)
    elif fw_lower == "actix" or fw_lower == "rust":
        return _generate_actix_backend(title, business_type)
    else:  # default: fastapi
        return _generate_fastapi_backend(title, business_type)


def _generate_fastapi_backend(title: str, business_type: str) -> Dict[str, str]:
    main_py = f'''# Standalone Dedicated FastAPI Backend Server for '{title}'
# Generated by Site Studio
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, EmailStr, Field
from typing import List, Optional
from datetime import datetime
import sqlite3
import os

app = FastAPI(
    title="{title} REST API",
    description="Production-ready standalone backend server for {title} ({business_type} domain).",
    version="1.0.0",
)

# CORS Middleware (Enables seamless local frontend integration)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DB_FILE = "app.db"

def init_db():
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS contacts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT NOT NULL,
            subject TEXT,
            message TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS leads (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT NOT NULL,
            phone TEXT,
            plan TEXT,
            notes TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS newsletter_subscribers (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT UNIQUE NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.commit()
    conn.close()

init_db()

# ── Pydantic Request Models ──────────────────────────────────────────
class ContactRequest(BaseModel):
    name: str = Field(..., min_length=2, max_length=100)
    email: str = Field(..., max_length=150)
    subject: Optional[str] = "General Inquiry"
    message: str = Field(..., min_length=5, max_length=2000)

class LeadRequest(BaseModel):
    name: str = Field(..., min_length=2, max_length=100)
    email: str = Field(..., max_length=150)
    phone: Optional[str] = None
    plan: Optional[str] = "Standard"
    notes: Optional[str] = None

class NewsletterRequest(BaseModel):
    email: str = Field(..., max_length=150)

# ── API Endpoints ────────────────────────────────────────────────────
@app.get("/")
def root():
    return {{
        "service": "{title} REST API",
        "status": "online",
        "database": "SQLite (app.db)",
        "docs_url": "/docs",
        "endpoints": [
            "GET  /api/health",
            "GET  /api/stats",
            "POST /api/contact",
            "POST /api/leads",
            "POST /api/newsletter",
            "GET  /api/contacts"
        ]
    }}

@app.get("/api/health")
def health_check():
    return {{
        "status": "healthy",
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "service": "{title} Backend Engine"
    }}

@app.get("/api/stats")
def get_stats():
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM contacts")
    contacts_count = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(*) FROM leads")
    leads_count = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(*) FROM newsletter_subscribers")
    subscribers_count = cursor.fetchone()[0]
    conn.close()
    return {{
        "total_contacts": contacts_count,
        "total_leads": leads_count,
        "total_subscribers": subscribers_count
    }}

@app.post("/api/contact", status_code=status.HTTP_201_CREATED)
def submit_contact(req: ContactRequest):
    try:
        conn = sqlite3.connect(DB_FILE)
        cursor = conn.cursor()
        cursor.execute(
            "INSERT INTO contacts (name, email, subject, message) VALUES (?, ?, ?, ?)",
            (req.name.strip(), req.email.strip(), (req.subject or "").strip(), req.message.strip())
        )
        conn.commit()
        contact_id = cursor.lastrowid
        conn.close()
        return {{
            "success": True,
            "message": "Thank you! Your message has been received.",
            "contact_id": contact_id
        }}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Database error: {{str(e)}}")

@app.post("/api/leads", status_code=status.HTTP_201_CREATED)
def capture_lead(req: LeadRequest):
    try:
        conn = sqlite3.connect(DB_FILE)
        cursor = conn.cursor()
        cursor.execute(
            "INSERT INTO leads (name, email, phone, plan, notes) VALUES (?, ?, ?, ?, ?)",
            (req.name.strip(), req.email.strip(), (req.phone or "").strip(), req.plan, (req.notes or "").strip())
        )
        conn.commit()
        lead_id = cursor.lastrowid
        conn.close()
        return {{
            "success": True,
            "message": "Lead captured successfully! Our team will contact you shortly.",
            "lead_id": lead_id
        }}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Database error: {{str(e)}}")

@app.post("/api/newsletter", status_code=status.HTTP_201_CREATED)
def subscribe_newsletter(req: NewsletterRequest):
    try:
        conn = sqlite3.connect(DB_FILE)
        cursor = conn.cursor()
        cursor.execute(
            "INSERT OR IGNORE INTO newsletter_subscribers (email) VALUES (?)",
            (req.email.strip().lower(),)
        )
        conn.commit()
        conn.close()
        return {{
            "success": True,
            "message": "Subscribed to newsletter updates successfully!"
        }}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Database error: {{str(e)}}")

@app.get("/api/contacts")
def list_contacts():
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM contacts ORDER BY id DESC LIMIT 50")
    rows = [dict(row) for row in cursor.fetchall()]
    conn.close()
    return {{"contacts": rows}}
'''

    requirements_txt = """fastapi>=0.100.0
uvicorn>=0.22.0
pydantic>=2.0.0
"""

    readme_md = f"""# {title} — Standalone FastAPI Backend Server

## Features
- **FastAPI (Python 3.12)** async REST API with interactive Swagger OpenAPI documentation at `/docs`.
- **Pre-Configured CORS** accepting requests from any frontend port.
- **Embedded SQLite Database (`app.db`)** with tables for Contacts, Leads, and Newsletter subscribers.
- **Active Endpoints**:
  - `POST /api/contact` — Ingest visitor contact messages.
  - `POST /api/leads` — Capture project inquiries and sales leads.
  - `POST /api/newsletter` — Store newsletter subscriber emails.
  - `GET /api/stats` — Real-time metrics.
  - `GET /api/health` — Service health check.

## Quick Start
```bash
pip install -r requirements.txt
python -m uvicorn main:app --reload --port 8001
```
Open **`http://localhost:8001/docs`** in your browser to test the API endpoints interactively.
"""

    return {
        "main.py": main_py,
        "requirements.txt": requirements_txt,
        "README.md": readme_md,
    }


def _generate_express_backend(title: str, business_type: str) -> Dict[str, str]:
    package_json = f"""{{
  "name": "dedicated-express-backend",
  "version": "1.0.0",
  "description": "Standalone Express.js backend for {title}",
  "type": "module",
  "main": "server.js",
  "scripts": {{
    "start": "node server.js",
    "dev": "node --watch server.js"
  }},
  "dependencies": {{
    "cors": "^2.8.5",
    "express": "^4.19.2",
    "sqlite3": "^5.1.7"
  }}
}}
"""

    server_js = f"""// Standalone Express.js REST API Server for '{title}'
// Generated by Site Studio
import express from 'express';
import cors from 'cors';
import sqlite3 from 'sqlite3';
import path from 'path';
import {{ fileURLToPath }} from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 8001;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({{ extended: true }}));

// SQLite Database Setup
const dbPath = path.resolve(__dirname, 'app.db');
const db = new sqlite3.Database(dbPath, (err) => {{
  if (err) {{
    console.error('Failed to open SQLite database:', err.message);
  }} else {{
    console.log('Connected to local SQLite database at:', dbPath);
    initDatabase();
  }}
}});

function initDatabase() {{
  db.serialize(() => {{
    db.run(`
      CREATE TABLE IF NOT EXISTS contacts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        email TEXT NOT NULL,
        subject TEXT,
        message TEXT NOT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
      )
    `);
    db.run(`
      CREATE TABLE IF NOT EXISTS leads (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        email TEXT NOT NULL,
        phone TEXT,
        plan TEXT,
        notes TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
      )
    `);
    db.run(`
      CREATE TABLE IF NOT EXISTS newsletter_subscribers (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        email TEXT UNIQUE NOT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
      )
    `);
  }});
}}

// ── Endpoints ────────────────────────────────────────────────────────
app.get('/', (req, res) => {{
  res.json({{
    service: '{title} Express REST API',
    status: 'online',
    database: 'SQLite (app.db)',
    endpoints: [
      'GET  /api/health',
      'GET  /api/stats',
      'POST /api/contact',
      'POST /api/leads',
      'POST /api/newsletter',
      'GET  /api/contacts'
    ]
  }});
}});

app.get('/api/health', (req, res) => {{
  res.json({{
    status: 'healthy',
    timestamp: new Date().toISOString(),
    service: '{title} Express Engine'
  }});
}});

app.get('/api/stats', (req, res) => {{
  db.get('SELECT COUNT(*) AS total_contacts FROM contacts', [], (err, row1) => {{
    if (err) return res.status(500).json({{ error: err.message }});
    db.get('SELECT COUNT(*) AS total_leads FROM leads', [], (err, row2) => {{
      if (err) return res.status(500).json({{ error: err.message }});
      db.get('SELECT COUNT(*) AS total_subscribers FROM newsletter_subscribers', [], (err, row3) => {{
        if (err) return res.status(500).json({{ error: err.message }});
        res.json({{
          total_contacts: row1.total_contacts,
          total_leads: row2.total_leads,
          total_subscribers: row3.total_subscribers
        }});
      }});
    }});
  }});
}});

app.post('/api/contact', (req, res) => {{
  const {{ name, email, subject, message }} = req.body;
  if (!name || !email || !message) {{
    return res.status(400).json({{ error: 'Please provide name, email, and message.' }});
  }}

  const stmt = db.prepare('INSERT INTO contacts (name, email, subject, message) VALUES (?, ?, ?, ?)');
  stmt.run([name.trim(), email.trim(), (subject || '').trim(), message.trim()], function (err) {{
    if (err) {{
      return res.status(500).json({{ error: err.message }});
    }}
    res.status(201).json({{
      success: true,
      message: 'Thank you! Your message has been received.',
      contact_id: this.lastID
    }});
  }});
  stmt.finalize();
}});

app.post('/api/leads', (req, res) => {{
  const {{ name, email, phone, plan, notes }} = req.body;
  if (!name || !email) {{
    return res.status(400).json({{ error: 'Please provide name and email.' }});
  }}

  const stmt = db.prepare('INSERT INTO leads (name, email, phone, plan, notes) VALUES (?, ?, ?, ?, ?)');
  stmt.run([name.trim(), email.trim(), (phone || '').trim(), plan || 'Standard', (notes || '').trim()], function (err) {{
    if (err) {{
      return res.status(500).json({{ error: err.message }});
    }}
    res.status(201).json({{
      success: true,
      message: 'Lead captured successfully! Our team will contact you shortly.',
      lead_id: this.lastID
    }});
  }});
  stmt.finalize();
}});

app.post('/api/newsletter', (req, res) => {{
  const {{ email }} = req.body;
  if (!email) {{
    return res.status(400).json({{ error: 'Please provide a valid email address.' }});
  }}

  const stmt = db.prepare('INSERT OR IGNORE INTO newsletter_subscribers (email) VALUES (?)');
  stmt.run([email.trim().toLowerCase()], function (err) {{
    if (err) {{
      return res.status(500).json({{ error: err.message }});
    }}
    res.status(201).json({{
      success: true,
      message: 'Subscribed to newsletter updates successfully!'
    }});
  }});
  stmt.finalize();
}});

app.get('/api/contacts', (req, res) => {{
  db.all('SELECT * FROM contacts ORDER BY id DESC LIMIT 50', [], (err, rows) => {{
    if (err) return res.status(500).json({{ error: err.message }});
    res.json({{ contacts: rows }});
  }});
}});

app.listen(PORT, () => {{
  console.log(`🚀 {title} Express Backend Server running on http://localhost:${{PORT}}`);
}});
"""

    readme_md = f"""# {title} — Standalone Express.js Backend Server

## Quick Start
```bash
npm install
npm run dev
```
Server runs locally at **`http://localhost:8001`**.
"""

    return {
        "package.json": package_json,
        "server.js": server_js,
        "README.md": readme_md,
    }


def _generate_nestjs_backend(title: str, business_type: str) -> Dict[str, str]:
    package_json = f"""{{
  "name": "dedicated-nestjs-backend",
  "version": "1.0.0",
  "description": "Standalone NestJS backend for {title}",
  "scripts": {{
    "build": "nest build",
    "start": "nest start",
    "start:dev": "nest start --watch"
  }},
  "dependencies": {{
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",
    "@nestjs/platform-express": "^10.0.0",
    "reflect-metadata": "^0.2.0",
    "rxjs": "^7.8.1",
    "sqlite3": "^5.1.7"
  }},
  "devDependencies": {{
    "@nestjs/cli": "^10.0.0",
    "@types/express": "^4.17.17",
    "@types/node": "^20.3.1",
    "typescript": "^5.1.3"
  }}
}}
"""

    main_ts = f"""import {{ NestFactory }} from '@nestjs/core';
import {{ AppModule }} from './app.module';

async function bootstrap() {{
  const app = await NestFactory.create(AppModule);
  app.enableCors();
  const PORT = process.env.PORT || 8001;
  await app.listen(PORT);
  console.log(`🚀 {title} NestJS API running on: http://localhost:${{PORT}}`);
}}
bootstrap();
"""

    app_module_ts = """import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
"""

    app_controller_ts = f"""import {{ Controller, Get, Post, Body }} from '@nestjs/common';
import {{ AppService }} from './app.service';

@Controller('api')
export class AppController {{
  constructor(private readonly appService: AppService) {{}}

  @Get('health')
  getHealth() {{
    return {{ status: 'healthy', service: '{title} NestJS Engine' }};
  }}

  @Get('stats')
  getStats() {{
    return this.appService.getStats();
  }}

  @Post('contact')
  submitContact(@Body() body: any) {{
    return this.appService.saveContact(body);
  }}

  @Post('newsletter')
  subscribeNewsletter(@Body() body: {{ email: string }}) {{
    return this.appService.saveSubscriber(body.email);
  }}
}}
"""

    app_service_ts = """import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  private contacts: any[] = [];
  private subscribers: string[] = [];

  getStats() {
    return {
      total_contacts: this.contacts.length,
      total_subscribers: this.subscribers.length,
    };
  }

  saveContact(data: any) {
    const record = { id: this.contacts.length + 1, ...data, created_at: new Date().toISOString() };
    this.contacts.push(record);
    return { success: true, message: 'Contact saved successfully.', contact_id: record.id };
  }

  saveSubscriber(email: string) {
    if (!this.subscribers.includes(email)) {
      this.subscribers.push(email);
    }
    return { success: true, message: 'Subscribed to newsletter successfully!' };
  }
}
"""

    readme_md = f"""# {title} — Standalone NestJS Backend Server

## Quick Start
```bash
npm install
npm run start:dev
```
Runs at `http://localhost:8001/api`.
"""

    return {
        "package.json": package_json,
        "src/main.ts": main_ts,
        "src/app.module.ts": app_module_ts,
        "src/app.controller.ts": app_controller_ts,
        "src/app.service.ts": app_service_ts,
        "README.md": readme_md,
    }


def _generate_django_backend(title: str, business_type: str) -> Dict[str, str]:
    requirements_txt = """django>=5.0
djangorestframework>=3.14.0
django-cors-headers>=4.3.0
"""

    manage_py = """#!/usr/bin/env python
import os
import sys

def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend_project.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH?"
        ) from exc
    execute_from_command_line(sys.argv)

if __name__ == '__main__':
    main()
"""

    settings_py = f"""import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'site-studio-template-secret-key'
DEBUG = True
ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_project.urls'
CORS_ALLOW_ALL_ORIGINS = True

DATABASES = {{
    'default': {{
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }}
}}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
"""

    urls_py = """from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]
"""

    api_models_py = """from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200, blank=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Lead(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=50, blank=True)
    plan = models.CharField(max_length=50, default='Standard')
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
"""

    api_views_py = f"""from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .models import Contact, Lead

@api_view(['GET'])
def health_check(request):
    return Response({{'status': 'healthy', 'service': '{title} Django REST API'}})

@api_view(['POST'])
def contact_create(request):
    data = request.data
    Contact.objects.create(
        name=data.get('name', ''),
        email=data.get('email', ''),
        subject=data.get('subject', ''),
        message=data.get('message', '')
    )
    return Response({{'success': True, 'message': 'Thank you! Your message has been saved.'}}, status=status.HTTP_201_CREATED)
"""

    api_urls_py = """from django.urls import path
from . import views

urlpatterns = [
    path('health', views.health_check),
    path('contact', views.contact_create),
]
"""

    readme_md = f"""# {title} — Standalone Django Backend Server

## Quick Start
```bash
pip install -r requirements.txt
python manage.py migrate
python manage.py runserver 8001
```
Runs at `http://localhost:8001/api/`.
"""

    return {
        "manage.py": manage_py,
        "backend_project/settings.py": settings_py,
        "backend_project/urls.py": urls_py,
        "backend_project/__init__.py": "",
        "api/models.py": api_models_py,
        "api/views.py": api_views_py,
        "api/urls.py": api_urls_py,
        "api/__init__.py": "",
        "requirements.txt": requirements_txt,
        "README.md": readme_md,
    }


def _generate_springboot_backend(title: str, business_type: str) -> Dict[str, str]:
    pom_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
        <relativePath/>
    </parent>
    <groupId>com.sitestudio</groupId>
    <artifactId>template-backend</artifactId>
    <version>1.0.0</version>
    <name>{title} Backend</name>
    <properties>
        <java.version>21</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
"""

    app_java = """package com.sitestudio.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.*;
import org.springframework.context.annotation.Bean;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import java.util.Map;
import java.util.HashMap;

@SpringBootApplication
@RestController
@RequestMapping("/api")
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @GetMapping("/health")
    public Map<String, Object> health() {
        Map<String, Object> res = new HashMap<>();
        res.put("status", "healthy");
        res.put("framework", "Spring Boot 3 (Java 21)");
        return res;
    }

    @PostMapping("/contact")
    public Map<String, Object> contact(@RequestBody Map<String, String> body) {
        Map<String, Object> res = new HashMap<>();
        res.put("success", true);
        res.put("message", "Contact received successfully by Spring Boot backend!");
        return res;
    }

    @Bean
    public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurer() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry.addMapping("/**").allowedOrigins("*").allowedMethods("*");
            }
        };
    }
}
"""

    readme_md = f"""# {title} — Standalone Spring Boot 3 Backend Server

## Quick Start
```bash
./mvnw spring-boot:run
```
Runs at `http://localhost:8001/api`.
"""

    return {
        "pom.xml": pom_xml,
        "src/main/java/com/sitestudio/app/Application.java": app_java,
        "README.md": readme_md,
    }


def _generate_rails_backend(title: str, business_type: str) -> Dict[str, str]:
    gemfile = """source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 3.0.0'

gem 'rails', '~> 7.1.0'
gem 'sqlite3', '~> 1.4'
gem 'puma', '>= 5.0'
gem 'rack-cors'
"""

    routes_rb = """Rails.application.routes.draw do
  namespace :api do
    get 'health', to: 'application#health'
    post 'contact', to: 'application#contact'
  end
end
"""

    controller_rb = f"""class Api::ApplicationController < ActionController::API
  def health
    render json: {{ status: 'healthy', service: '{title} Rails 7 Engine' }}
  end

  def contact
    render json: {{ success: true, message: 'Message received by Rails API!' }}, status: :created
  end
end
"""

    readme_md = f"""# {title} — Standalone Ruby on Rails 7 Backend Server

## Quick Start
```bash
bundle install
rails server -p 8001
```
Runs at `http://localhost:8001/api`.
"""

    return {
        "Gemfile": gemfile,
        "config/routes.rb": routes_rb,
        "app/controllers/api/application_controller.rb": controller_rb,
        "README.md": readme_md,
    }


def _generate_laravel_backend(title: str, business_type: str) -> Dict[str, str]:
    composer_json = f"""{{
    "name": "sitestudio/template-backend",
    "type": "project",
    "description": "Standalone Laravel 11 backend for {title}",
    "require": {{
        "php": "^8.2",
        "laravel/framework": "^11.0"
    }}
}}
"""

    routes_api = f"""<?php

use Illuminate\\Support\\Facades\\Route;
use Illuminate\\Http\\Request;

Route::get('/health', function () {{
    return response()->json([
        'status' => 'healthy',
        'service' => '{title} Laravel 11 Backend'
    ]);
}});

Route::post('/contact', function (Request $request) {{
    return response()->json([
        'success' => true,
        'message' => 'Message successfully recorded by Laravel API!'
    ], 201);
}});
"""

    readme_md = f"""# {title} — Standalone Laravel 11 Backend Server

## Quick Start
```bash
composer install
php artisan serve --port=8001
```
Runs at `http://localhost:8001/api`.
"""

    return {
        "composer.json": composer_json,
        "routes/api.php": routes_api,
        "README.md": readme_md,
    }


def _generate_actix_backend(title: str, business_type: str) -> Dict[str, str]:
    cargo_toml = f"""[package]
name = "dedicated_actix_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.7"
serde = {{ version = "1.0", features = ["derive"] }}
serde_json = "1.0"
tokio = {{ version = "1", features = ["full"] }}
"""

    main_rs = f"""// Standalone Actix Web (Rust) Server for '{title}'
// Generated by Site Studio
use actix_cors::Cors;
use actix_web::{{get, post, web, App, HttpResponse, HttpServer, Responder}};
use serde::{{Deserialize, Serialize}};

#[derive(Serialize)]
struct HealthResponse {{
    status: String,
    service: String,
}}

#[derive(Deserialize)]
struct ContactForm {{
    name: String,
    email: String,
    message: String,
}}

#[derive(Serialize)]
struct ApiResponse {{
    success: bool,
    message: String,
}}

#[get("/api/health")]
async fn health() -> impl Responder {{
    HttpResponse::Ok().json(HealthResponse {{
        status: "healthy".to_string(),
        service: "{title} Actix Web (Rust) Server".to_string(),
    }})
}}

#[post("/api/contact")]
async fn contact(form: web::Json<ContactForm>) -> impl Responder {{
    println!("Received contact inquiry from: {{}} (<{{}}>)", form.name, form.email);
    HttpResponse::Created().json(ApiResponse {{
        success: true,
        message: "Thank you! Your message was received by the Rust Actix server.".to_string(),
    }})
}}

#[actix_web::main]
async fn main() -> std::io::Result<()> {{
    println!("🚀 {title} Actix Web Server running on http://127.0.0.1:8001");
    HttpServer::new(|| {{
        let cors = Cors::permissive();
        App::new()
            .wrap(cors)
            .service(health)
            .service(contact)
    }})
    .bind(("127.0.0.1", 8001))?
    .run()
    .await
}}
"""

    readme_md = f"""# {title} — Standalone Actix Web (Rust) Backend Server

## Quick Start
```bash
cargo run
```
Runs at `http://127.0.0.1:8001/api`.
"""

    return {
        "Cargo.toml": cargo_toml,
        "src/main.rs": main_rs,
        "README.md": readme_md,
    }
