"""add_seller_payout_details

Revision ID: 02d870fe3398
Revises: 82676b96fccc
Create Date: 2026-07-29 17:29:04.235202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d870fe3398'
down_revision: Union[str, None] = '82676b96fccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payout_bank_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('payout_account_number', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('payout_ifsc_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('payout_account_holder_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_payout_setup_completed', sa.Boolean(), nullable=True))
    
    # Populate existing rows
    op.execute("UPDATE users SET is_payout_setup_completed = FALSE")
    
    # Enforce NOT NULL constraint
    op.alter_column('users', 'is_payout_setup_completed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_payout_setup_completed')
    op.drop_column('users', 'payout_account_holder_name')
    op.drop_column('users', 'payout_ifsc_code')
    op.drop_column('users', 'payout_account_number')
    op.drop_column('users', 'payout_bank_name')
    # ### end Alembic commands ###
